### ISSUE TITLE
[Bug] Always redirects to main page (NGINX)

### ISSUE THREAD

**Issue by devilAPI** [boxbilling/boxbilling#1032]
### What happened?

Hey, so first of all, I didn't get the `sef_urls` to work on apache, so i gave nginx a try.
So i have absolutely no idea of how Nginx works, but I want to stick with it for my current installation.

Problem is when opening (for example) /bb-admin, it redirects to the home page, its impossible to register, order, open admin panel whatever...

This is my server config:
[Hastebin](https://hastebin.com/inuhagaxar.nginx)

Can someone tell me whats wrong with it? I dont think thats the problem, but heres my BoxBilling config:
`<redacted>`

### BoxBilling Version

v4.22-beta.1

### What version of PHP are you running?

PHP 7.4

### Additional Notes

Additional notes

**Comment by devilAPI** [comment]
I also cant login with my email and pass when trying to login at `/index.php?_url=/bb-admin/staff/login`

![Screenshot 2021-09-16 181920](https://user-images.githubusercontent.com/52862870/133648763-e0dcd935-523b-45b4-987d-008674ac3227.png)

**Comment by BenNottelling** [comment]
Uh, well technically I don't think `sef_urls` are supposed to work on nginx

**Comment by devilAPI** [comment]
Dosent work with this config too:

https://hastebin.com/osisahakex.php

**Comment by timothygwebb** [comment]
Security recommendations never put your database login credentials online.

I have accessed your phpmyadmin interface to see if the specified user has
permission to access anything it is obvious that this user has no
assigned access permission in the MySQL database.

Please see attached screenshot

I would recommend that you execute the following command to assign this
user privileges.

*mysql> GRANT ALL PRIVILEGES ON servohosting_sql*. * TO 'boxbilling_sql'@
'localhost';

Then reset the user password and update your config file and remove it from
hastebin.

**Comment by devilAPI** [comment]
I actually noticed that my password was on the hastebin abt. 1 hour after posting, so how'd you get access to the account?

**Comment by devilAPI** [comment]
I will close the problem now as I have changed my mind anyway and will now be using different software.

**Comment by timothygwebb** [comment]
I did not get access to the account. I know in most default setups all
configurations of available software to support the product to do failure
verification using phpmyadmin with which authentication is completed via
the MySQL database named MySQL with the containing user table. This tells
me that the named account does not exist or have the required permission to
login to not only BoxBilling but PhpMyAdmin as well. I was informing you to
take it down because someone could use SQL injection with the information
provided to try and do a privilege escalation attack against your system.
Code provided to resolve the issue I gave you from experience on how to
update and fix your issue. I would recommend you to review the following
websites https://docs.phpmyadmin.net/en/latest/privileges.html ,
https://dev.mysql.com/doc/refman/8.0/ en/creating-accounts.html , and
http://dev.mysql.com/doc/refman/5.0/en/default-privileges.html

Thanks
