### ISSUE TITLE
Bitcoin as Currency

### ISSUE THREAD

**Issue by dadistributedweb** [boxbilling/boxbilling#1214]
### What is the idea?

I'm willing to support/pay/donate to someone who creates a module and/or functionality that allows invoicing clients in Bitcoin (BTC). I guess, for that BTC has to be added as currency in the Boxbilling system and it should pull data for the actual BTC/USD exchange rate from a credible source.  

### Why would this be beneficial

This will allow many companies that sells in BTC to use Boxbilling and will increase the CRM's user base.

**Comment by notbasetwo** [comment]
I don't know many firms who would use this rather than charging in USD and having their gateway (i.e. BitPay) handle the transaction fee (it's so wild that I'm not sure doing it locally would be very helpful).

**Comment by DJTerrum** [comment]
> Thank you @notbasetwo. I did not ask does anyone know firms that would do that :) I have asked is there anyone who would be willing to create a module and/or functionality that allows invoicing clients in Bitcoin (BTC)! And we are wiling to pay for that. Are you willing to help here or it is just a general comment, which I appreciate?
I assume it's a general comment, but also one that is there to inform you that it is unlikely this request will ever be filled, due to lack of demand and other reasons that they mentioned.
Using a merchant such as BitPay which handles the currency conversions etc for you would make much more sense because coding a BTC currency for BoxBilling would be too inefficient.

**Comment by 0x6b-dev** [comment]
[Duplicate #1250](https://github.com/boxbilling/boxbilling/issues/1250)

**Comment by 0x6b-dev** [comment]
Closed in favour of #1250
