### ISSUE TITLE
Cache file not showing up during both composer install and unziping of contents

### ISSUE THREAD

**Issue by waylenwasywas** [boxbilling/boxbilling#1377]
When first accessing the install page, the cache file that is supposed to be located within bb-data/ isn't there. I have attempted to go past it however, I cannot open pages such as the admin panel or any others outside of the client area. I hope I am just messing something up. Thank you.

**Comment by evrifaessa** [comment]
Create a directory in bb-data named "cache". Make sure your web server can read and write files in that folder.

Also, due to some problems with the original author, the team had to move to a new organization called FOSSBilling.

You can get more information from our website: https://fossbilling.org. We also have a Discord server, [you can click here to join](https://fossbilling.org/discord).

**Comment by waylenwasywas** [comment]
Awesome, thank you!
