### ISSUE TITLE
Currency not found

### ISSUE THREAD

**Issue by corianito** [boxbilling/boxbilling#160]
Clicking on subscriptions shows this error = 500

An exception has been thrown during the rendering of a template ("Currency not found") in "layout_default.phtml" at line 106.!

I removed the dollar and I left only the euro

**Comment by pkminer30** [comment]
Heres the fix:

Go to mysql
Go to clients: go to each entry for client and set currency field to currency code from currency table e.g. GBP.

Then update currency table with currency value and wipe all orders and invoices for previous orders.

This should fix the issue. Easy fix for boxbilling would be to make it so that on updating currency it runs a update query against clients table where "old" currency gets updated.
