### ISSUE TITLE
Currency not found

### ISSUE THREAD

**Issue by legion726** [boxbilling/boxbilling#227]
An exception has been thrown during the rendering of a template ("Currency not found") in "mod_invoice_invoice.phtml" at line 574.

Look for detailed error explanation
Set BB_DEBUG to FALSE, to hide the message below

Class: "Twig_Error_Runtime"

File: "/home/netengi/domains/new.netengi.com/public_html/bb-vendor/twig/twig/lib/Twig/Template.php"

Line: "148"
in http://new.netengi.com/index.php?_url=/bb-admin/invoice/manage/11

(after paying with a payment module). 
tell me how to fix
module http://pastie.org/9832115

**Comment by legion726** [comment]
close

**Comment by pkminer30** [comment]
Heres the fix:

Go to mysql
Go to clients: go to each entry for client and set currency field to currency code from currency table e.g. GBP.

Then update currency table with currency value and wipe all orders and invoices for previous orders.

This should fix the issue. Easy fix for boxbilling would be to make it so that on updating currency it runs a update query against clients table where "old" currency gets updated.
