### ISSUE TITLE
Problem with invoice variables ! 

### ISSUE THREAD

**Issue by chechohack** [boxbilling/boxbilling#253]
I have found the following variables for the invoices:

    {{invoice.id}}
    {{invoice.number}}
    {{invoice.title}}
    {{invoice.subtotal}}
    {{invoice.total}}
    {{invoice.tax}}
    {{invoice.currency}}

but when i try use the variable {{invoice.title}} in html, this shows me an empty field.

This variables has changed ?

Thanks for your help.

**Comment by 4Giedrius** [comment]
Where did you find `{{invoice.title}}` variable? Invoice does not have a title, instead it has `nr` and `serie` variables and you can use them to create a title. However I think that there might be some confusion because all of invoice items have their title variable. You can print all of them using `foreach` loop:

    {% for item in invoice.lines %}
        {{ item.title }}
    {% endfor %}

**Comment by lukapaunovic** [comment]
I am looking forward in displaying in my custom payment gateway client info.
I can not do manage that with {{ c.first_name }}
Nothing is output
But with this you posted
{% for item in invoice.lines %}
    {{ item.title }}
{% endfor %}
It displays something!
What is FOR ITEM for first name, address and invoice number?
