### ISSUE TITLE
Missing support for OpenSRS and Namecheap

### ISSUE THREAD

**Issue by hackersrage** [boxbilling/boxbilling#294]
Current release is missing the following domain registrars :

   OpenSRS
   dotTk
   Namecheap

**Comment by vaidas-lungis** [comment]
DotTk was removed from BoxBilling official support. https://github.com/boxbilling/boxbilling/issues/255#issuecomment-73515154

BoxBilling development team is solely responsible for developing core and main functionality. Since BoxBilling is open source modular application, you can add features of your choice and extend BoxBilling. It can be done by adding new BoxBilling extension. If you are not familiar with how to do that, please have a look at BoxBilling documentation, we have prepared Example module to get you started. If you need any help developing extension please use BoxBilling forum.
Source code can be found at [GitHub's BoxBilling repository](https://github.com/boxbilling/boxbilling). 

If you have problems creating new module or implementing new functionality, please use our [contact form](http://www.boxbilling.com/contact-us) and request a quote. Try to detail your problem as much as possible so that we could understand what exactly needs to be done.

**Comment by hackersrage** [comment]
Thank you for your reply.

I found I had the dottk module in the wrong location, however I am looking into the false negative issue and will attempt to correct it.  If i get this module fully functional, I will submit a pull request for your review.

Regarding the other methods, I have submitted a ticket at the link provided (thank you for that), and included a link to the API documentation for Namecheap's SSL services.

I will be submitting a pull request for the latest OpenSRS php library although I do notice you have this in your dev build.

**Comment by hackersrage** [comment]
https://github.com/boxbilling/boxbilling/pull/295 DotTK support is now functional with this pull request.

**Comment by 4Giedrius** [comment]
As @vaidas-lungis said we have decided to drop support for DotTK registrar and moved it to our [extensions repository](https://github.com/boxbilling/boxbilling). Please open pull request there.

**Comment by evrifaessa** [comment]
> This issue is marked as closed but I can't find OpenSRS support anywhere?

@ralphonz - I'd suggest you to create an issue related to this in our fork named [FOSSBilling](https://github.com/FOSSBilling/FOSSBilling). As the majority of the latest team, we had to move to a new organization due to the problems arising from the fact that the BoxBilling project is dependent on a single person. We now have more flexibility and an active development environment in the new organization.

We also have a Discord community. If you want to join, [here](https://fossbilling.org/discord) is the link. The codebase is the same and we're planning to make a new release soon. Until then, preview builds are automatically being generated and made available on our [website](https://fossbilling.org).
