### ISSUE TITLE
Allow modification of client details after order has been created but before service is activated

### ISSUE THREAD

**Issue by HansAdema** [boxbilling/boxbilling#339]
When a new domain registration order is created, the details are pulled from the client profile. However, if these details are invalid for whatever reason, there currently does not seem to be a way to modify them without manually changing the service in the database.

The easy solution would be to simply get the client details when activating the order, rather than when trying to create it. The pretty solution would be to get forms in both the client and admin area where the pending order can be modified. However, I would prefer to leave the actual design decision up to you.

**Comment by vaidas-lungis** [comment]
You can edit order config at bb-admin/order/manage "edit order config" tab and client profile data can be edited in profile page. Client profile information is fetched from database every service management action.

**Comment by i7Grendel** [comment]
Thank you for your response. Unfortunately, there do no seem to be any fields for client profile details on the Edit Order Config tab. There are plenty of values there, including nameservers, title and price, but no contact or profile details.

**Comment by samapco** [comment]
This issue is caused by the if statement on line 89 in bb-themes\admin_default\html\mod_servicedomain_manage.phtml
line 89: {% if order.status == 'active' %}  endif on line 267

Commenting line 89 and line 267 makes it possible to modify the user details
{#% if order.status == 'active' %#}
{#% endif %#}

You would also have to provide a value for address line 2 else you cannot save the details. I don't know why  the dev team made 'address line 2' field a required field.
