### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Currency not found") in "mod_invoice_index.phtml" at line 146.

### ISSUE THREAD

**Issue by Akuukis** [boxbilling/boxbilling#363]
I want to change currency after testing/tinkering with Boxbilling but get error.

Redo:
1. Fresh install
2. Add client
3. **Add invoice with default (USD) currency**
3. In settings add other currency, make it default and **remove USD currency**
4. Try to open any Invoice page (for example Invoices>Overview) to get error

Workaround:
1. Add back USD currency
2. Delete all USD invoices
3. Remove USD currency

Also get similar error `An exception has been thrown during the rendering of a template ("Currency not found") in "mod_client_manage.phtml" at line 384.` when editing user with removed currency or adding him to new invoice.

I think Boxbilling should solve the problem itself or ask to temporarily add back currency instead of throwing error.

**Comment by pkminer30** [comment]
Heres the fix:

Go to mysql
Go to clients: go to each entry for client and set currency field to currency code from currency table e.g. GBP.

Then update currency table with currency value and wipe all orders and invoices for previous orders.

This should fix the issue. Easy fix for boxbilling would be to make it so that on updating currency it runs a update query against clients table where "old" currency gets updated.
