### ISSUE TITLE
Licencing has holes

### ISSUE THREAD

**Issue by KaidenP** [boxbilling/boxbilling#368]
Your licensing system is really easy to patch, But if you would like, I could modify it so it is much harder.

**Comment by 4Giedrius** [comment]
Could you elaborate more on your statement?

**Comment by gOOvER** [comment]
Why patching?  Boxbilling is  OpenSource and everyone can remove it,  like he want ;)  So modifying to make it harder is senseless ;) Everyone would see you changes and revert it ;)

**Comment by kkprince1998** [comment]
I was thinking of modifying the license code so it verifies that the response is verified via some sort of publickey privatekey. This way it verifies that the response actually came from your license server, not some server created locally, ie http://i-mscp.net/index.php/Thread/5840-BoxBilling-PRO-license-hack/ or simalar. Using a local licence server like above means that it always works, even after updates.

With my idea, people will still easily modify the code locally, but after each update they have to modify again. this annoyance may help people to support the project by purchasing licenses.

**Comment by gOOvER** [comment]
lol, the i-MSCP Licence Hack is s bit to difficult. You can remove 
licence check easierly. ;) But this is not the sense of OpenSource... ;) 
And if you commit it, everyone can remove it easily, because changes are 
posted on Github.......... :) So why adding this Licence check.... 
Normally this should be removed... as i said in past Comments, because 
it's totally senseless...

BEst Way foir dev's to get Money; release payed Addons ;)

------ Originalnachricht ------
Von: "Kaiden Prince" <notifications@github.com>
An: "boxbilling/boxbilling" <boxbilling@noreply.github.com>
Cc: "Torsten Widmann" <goover0976@googlemail.com>
Gesendet: 24.08.2015 18:17:59
Betreff: Re: [boxbilling] Licencing has holes (#368)

**Comment by kkprince1998** [comment]
I actually did it quite easily:

/etc/hosts:
```
127.0.0.1 www.boxbilling.com
```
{wwwRoot}/api/guest/servicelicense/check
```json
{"result":{"licensed_to":"EVERYONE","created_at":"2015-08-06T11:07:01+00:00","expires_at":"","valid":true,"error":null,"error_code":null},"error":null}
```

Mow everyone on my dev server has bb pro.

**Comment by kkprince1998** [comment]
As for paid addons, what might that be?

**Comment by i7Grendel** [comment]
I personally use a cracked license module which does not listen to a license server at all. I just configured all methods to return sample data, which is faster than calling a remote server.

However, I agree that the licensing system should be removed entirely. Limiting how many products someone can have in a free (as in free speech) system is ridiculous and means only those who can write code can use additional features.

Instead they could opt for the Elastico model and offer enterprise addons (although that would mean BoxBilling competed directly with WHMCS, something they cannot win) or go for the Red Hat model and offer paid support.
