### ISSUE TITLE
Poxmox Integration

### ISSUE THREAD

**Issue by ikhode** [boxbilling/boxbilling#433]
It would be great if they integrate VPS Proxmox api to manage client-side and administrator.

**Comment by scith** [comment]
Hello, I'm coding this module at the moment! A first version will be ready over the next few months. Id appreciate if you could be a tester then... but the first version will be quite rudimentary

**Comment by Toggie** [comment]
scith: I am happy to test as well.

**Comment by fossxplorer** [comment]
Hi @scith 
Great if you are adding Proxmox support.
May we ask more details about it? 
I'll also help with testing.

**Comment by scith** [comment]
Hi @fossxplorer 
Yes sure. I'm using the Proxmox PHP API https://github.com/CpuID/pve2-api-php-client
I'm using a dedicated plugin rather than a server lib because of the limitations detailed here: https://github.com/boxbilling/boxbilling/issues/431#issuecomment-183879705
The Proxmox hypervisors can be put in groups and the new orders are automatically allocated to one of the servers that has empty slots based on the rule chosen (fill the least filled server / fill up each server in turn)
The user can access the VNC console from the panel.

It is quite limited at the moment because the administration is quite tedious (I don't retrieve the available images, nodes, etc...) so it's done manually

Hopefully I'll have something for you to test in the next following months

**Comment by Technowix** [comment]
Any news on this ? :D

**Comment by scith** [comment]
Won't be until this summer I'm afraid...

**Comment by melvincornelissen** [comment]
Yay! Waiting for this 👍

**Comment by fossxplorer** [comment]
@scith Please let us know if you got something, i'm ready to test and give you feedback :)

**Comment by scith** [comment]
Thanks for the support! I'm trying to ship an alpha by mid-July. I've been busy on other projects sorry.

**Comment by Technowix** [comment]
Very nice theme @scith <3 and thanks for investement :D

**Comment by fossxplorer** [comment]
@scith 
mid-July fits very good to me. Now i need to start playing with Promox in the meanwhile, i'm pretty new to it. 
Also the boxbilling theme looks awesome, will hopefully give it a try as well. THX A LOT!

**Comment by scith** [comment]
I'm almost there... A few more tests to run
However, I face one major problem: How do I assign an IP to a LXC or QEMU VM? Or how do I retrieve the IP that has been assigned to the VM?
Without this information, I can't send the login details to the customer, which is embarassing...

Thanks

**Comment by Technowix** [comment]
You should store it somewhere in a admin area, and virtual mac adress too (for providers like OVH) :)

**Comment by scith** [comment]
Yep this I am doing already. The database and the admin panel can store the IP.
However, I don't know how to retrieve the IP of the VM I just created for the customer. Or instead how to allocate an IP to the order and then assign it to the VM.

I would like to send an automated email to the client with the IP of his/her VM and the login details

**Comment by scith** [comment]
**OK so here is the alpha version of my Proxmox module**: https://github.com/scith/BoxBilling_Proxmox
![QEMU dashboard](https://framapic.org/bcAMQ6sksIEz/632Eg9fKkyW5.JPG)

See [issues](https://github.com/scith/BoxBilling_Proxmox/issues) for the things left to be done... I need help on these.
Please post your issues [on the module git](https://github.com/scith/BoxBilling_Proxmox/issues) and feed your changes back as the module is GPL.

Thanks for the support and the testing @ikhode @Toggie @fossxplorer @melvincornelissen @Technowix
