### ISSUE TITLE
License not valid - issues

### ISSUE THREAD

**Issue by lukapaunovic** [boxbilling/boxbilling#498]
My server has 1 IPv4 address and a few IPv6 addresses.
Sometimes I can't login or client can't order because IP which is contacting licensing server changes.
and I need to reset license so it accepts a request from new IP...
How do I force BoxBilling to only use IPv4 so it uses 1 IP when checking license validity. 
This is really annoying and interrupting my work.

**Comment by lukapaunovic** [comment]
Solved

Edit file: **/bb-library/Box/License.php**

Add this after 198 line
```
if (defined('CURLOPT_IPRESOLVE') && defined('CURL_IPRESOLVE_V4')){
        curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
}
```

**Comment by thewolf9** [comment]
Didn't solve it for me

**Comment by TuxMay** [comment]
@thewolf9 Due to our licensing method, only one static IP address can be used. Could you please get in touch with us via our [Pre-Sales Contact Form](http://www.boxbilling.com/contact-us), include in your message the email address your free/pro license is associated with & all IP Addresses that you currently have on your hosting environment - we can help get this fixed for you.

**Note:** Do not use the email address associated with your account with us when completing the contact form.
