### ISSUE TITLE
BOXBILLING is DEAD

### ISSUE THREAD

**Issue by CptPlastic** [boxbilling/boxbilling#507]
Is there any active development going on for this project?

**Comment by StefvanEgmond** [comment]
Any forks active?

**Comment by OnlyHardOfficial** [comment]
NOP! Its completelly DEAD! Try Someting like Blesta! Its Nice to ME!  and more  FLUID

**Comment by 62BRAINS** [comment]
There were comments last year about a complete rewrite, and several fixes offered in PRs that didn't seem to be of interest. With 203 forks of this code, I can't image a complete loss of interest.

I am interested in keeping this going. Anyone interested in building a team to take it on?

**Comment by Eiskaltereistee** [comment]
@62BRAINS I am interested to continue the boxbilling work. I already did some bug fixes, PHP 7 support and so on some months ago.

Let's create a team and start working on a new version!

Maybe we can use slack for some discussions?

**Comment by StefvanEgmond** [comment]
Shall I do a startup? I am highly interested. We should set up a community to rebuild and expand BoxBilling.

**Comment by Eiskaltereistee** [comment]
@StefvanEgmond I already wrote with @62BRAINS and we've created a slack workspace to discuss about the topic boxbillig. 
Please let me know if you are intrested to take part of our discussion. 

You can email me to kontakt@jonah-bohlmann.de that I can send you an invation for slack.

I would be happy to hear from you!

**Comment by NatarajaVj** [comment]
Hi All, 

This is an awesome news!! yes bring box to life!
I happy to help & would like to be part of the discussion if possible .. 
@Eiskaltereistee will send you a mail .. 

Regards,

**Comment by StefvanEgmond** [comment]
Sent an email! Would be happy to get a reply soon!

**Comment by OnlyHardOfficial** [comment]
this is good news. I will be able to help with some resources that I can make available!

**Comment by TuxMay** [comment]
You have a Slack account for BoxBilling?

Just to clarify guys, if you have new feature's you want to get released on this GitHub, I'll be more than happy to get them on here & provide credit to those that developed it - the community for BoxBilling is vital for BoxBilling. As you know BoxBilling went open-source two-three years ago now, this was so developers can better develop further BoxBilling without relying on the developers of BoxBilling. Features include PHP 7.x support, bug fixes, patches & module updates (E.g. cPanel, Plesk, PayPal, Stripe etc.).

**Comment by namenodeis** [comment]
If you guys want help I have been learning the ins and outs of Boxbilling to develop a CentOS WebPanel extension. I only have a rudimentary version working at the moment, but I would love to help push development along. =)

**Comment by scith** [comment]
Hi
Feel free to use my bootstrap template if you wish. In my fork of boxbilling, I removed the licence checks and included this bootstrap theme as default
Cheers

**Comment by TuxMay** [comment]
If you have something you want to contribute to BoxBilling, send your info to: https://portal.mymbs.eu/boxbilling.php - we can get this onto this GitHub after we review the changes/modules you have done.

Again, I do not mind giving credit where it is due, if anyone wants to give some of our feature requests a go, do let us know using the above link.

**Comment by OnlyHardOfficial** [comment]
@Eiskaltereistee

**Comment by namenodeis** [comment]
@TuxMay if you are representing the official BB team, then might I suggest you guys compile fixes in to a new release. Also fix the boxbilling support forum it is unusable from bots. And fix the extensions.boxbilling.com site so it is available again. These are things that make the project look dead.
In the meantime joining [this other fork](https://github.com/CircleBilling/CircleBilling) sounds good.

**Comment by TuxMay** [comment]
@namenodeis I have been apart of BoxBilling for many years, it is not a recent start. If you have not noticed, the extensions sub-domain is not coming back as all stuff on it was put onto our GitHub as soon as the open source version was released.

I have already noticed the increase of spam bots trolling the forum, as such the forum was locked a few days ago while we start removing the 30,000+ (25,000 already removed) articles posted, as SPAM is not tolerated on our system, the forum will remain locked until further notice while an investigation is undertook and ISP notified of the SPAM.

I presume that version of BoxBilling is authorised for distribution, remember that BoxBilling still holds full authority over BoxBilling & all modules & components within it?

**Comment by namenodeis** [comment]
So you have a ETA for a new release? You plan to begin supporting the product officially again?

**Comment by Eiskaltereistee** [comment]
You can follow us: https://github.com/CircleBilling/CircleBilling

We're are a group of bb-lovers and want to continue bb under a different name. BB next generation. ;-)

We're happy for every follower!

**Comment by CptPlastic** [comment]
@TuxMay what are you trying to say? Sounds like these guys want to expand on the open version and have every right to do so. Just start a new forum??? The current version is outdated and in dire need of an overhaul. I would rewrite the entire extension integration anyhow.

**Comment by TuxMay** [comment]
That isn't the point, we don't mind you expanding on it & sharing it, but when you try to rebrand it to ciclebilling - without our knowledge, that is called theft.

**Comment by CptPlastic** [comment]
Pretty much why boxbilling is dead. It has not been updated in years but the moment someone interest is sparked @TuxMay comes in with the theft BS. I stopped using it long ago because i could never get it to pass a security scan. I hope you guys that want to make an actual supported and updated open billing platform do so. My advice is to just avoid this toxic crap all together.

**Comment by Eiskaltereistee** [comment]
@TuxMay maybe you should read and understand the apache licence agreement. You can find a short version on wikipedia: https://en.wikipedia.org/wiki/Apache_License

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

As you can see in our license file, boxbilling is still in there: "Copyright 2014 Boxbilling, Inc"

But there is a missing "NOTICE" file, so I will add them soon. 
If I'm wrong, please just quote from the Apache license.

**Comment by gOOvER** [comment]
Thats the Boxbilling Team in real and live.... ;)

http://prntscr.com/jlnbkn

**Comment by StefvanEgmond** [comment]
Why are all issues closed?

**Comment by TuxMay** [comment]
All Issues were closed due to outdated issues so we are starting fresh, any new issues will be looked at, but may not be responded too, as this software is open source, we are hoping fans/developers of the BoxBilling software will help resolve new issues.

**Comment by StefvanEgmond** [comment]
I don't think BB has any fans left since it didn't updated for 2 years

**Comment by TuxMay** [comment]
That is your opinion, yet from the activity on this GitHub & the support ticket requests we still receive state otherwise.

**Comment by gOOvER** [comment]
I think, this will be the same linke 2 years before. Now you see, that a fork started and noch you will be active. I bet, it will  be quite again in 1 til 2 months again. Sry, ihave BB now since 5 years and i hear a lot, what are you talking and doing and nothing comes real... Like v5 ;)

**Comment by Eiskaltereistee** [comment]
@TuxMay 
> from the activity on this GitHub

You mean the active "shitstorm" and angry users.. I thinks it's not the activity you need.. ;)

**Comment by TuxMay** [comment]
If you do not wish to help with the next version of BoxBilling, I really do not see why you have the need to view this GitHub in my opinion. The point of this GitHub is so users can help each other diagnose & fix issues such as those that were in the Issues, but allas I must be wrong & is just a place that users come to scream their anger to new users.

**Comment by StefvanEgmond** [comment]
I think I am not going to wait for 

@TuxMay 
>  the next version of BoxBilling

I'm seeing a future in https://github.com/CircleBilling/CircleBilling

**Comment by TuxMay** [comment]
Well I have one question for you, why are you still visiting this GitHub?

**Comment by kayazeren** [comment]
Dr Frankenstein was also thinking "He's alivee!" but...

**Comment by TuxMay** [comment]
@gOOvER I have removed links to this circlebilling GitHub project as it isn't being advertised on the BoxBilling GitHub. You state that we haven't been active on GitHub, I presume you mean responding to users & merging stuff, then you are correct, but we have been monitoring since the last version.

Again, why are you all on this GitHub if you are not going to help develop it, if you have no development for BoxBilling, then why are you here? Instead of getting aggressive towards me for being a member of the BoxBilling team, I'm not the developer of the software, I have not been here since v1.0 - I came into BoxBilling since v3.0 to help with the support ticket demand (200+ tickets per hour), yet because I started to respond & try to give updates to you, you backlash it in my face (or screen in this case).

MyMBS Networks started work on the v5.0 development but abandoned it due to no demand for it as everyone started to think it was dead. Development takes time & money. I admit the original BoxBilling developers may have dropped BoxBilling after v4.20, yet I will not give up on BoxBillling, yet in order to do that, I need time, developers & money towards the development - aka the reason why I stated if you do have any module updates, development updates, vulnerability patches etc, I would like to see them, review them & get them onto BoxBilling master to help get this v5 done!

**Comment by StefvanEgmond** [comment]
But still, we are not advertising [CircleBilling](https://github.com/CircleBilling/CircleBilling)
). We are suggesting helping us creating [CircleBilling](https://github.com/CircleBilling/CircleBilling).
Btw, we are not being agressive...

**Comment by namenodeis** [comment]
I came back to this Github because I do care about BoxBilling. The world needs a better FOSS Webhosting front-end. And I trudged through BB for a while in my first business attempt. Support for virtualizor and other emerging platforms, as well as payment gateway bugs and other issues drove me to tolerating WHMCS for a time. 

I would have gladly paid that money to BB had my experience seeking support there not been so unhelpful. I learned quickly the forum was a waste of time because no one was posting actual solutions or explanations. It was like, oh it's open-source go figure it out. 

And I am not a developer as my main gig. (Development is hard on us sysadmins we like that stuff figured out for us.) So fixing problems in other coder's applications is not just something I can always just go do.

So while I wanted BB to be this greater thing than it was, it became a big disappointment for me. And when I got a notification in Softaculous Admin area to turn it off because it was outdated/not maintained. I was reminded of this great script and all of its potential. 

As I searched around, I found a lot of other people like me, that really wanted to make it work for them, too. But the biggest issues usually had no real applicable solutions for an inexperienced developer or a non-developer.

But I give a s***, oddly enough. I wanted to go back with my knowledge since that time and bend BB to my will to make it work the way I want it, also.

And so I have been getting down to the nuts and bolts of PHP and not just reading over it. I have written an extension for CWP Server Manager already, the functions work, but it keeps giving me "backend fetch failed" 500 errors at the end of each task - i.e. suspend, unsuspend, create account, even though the actions succeed on the host.  So I will not publish it until I can better understanding of using github AND fixing it so that this backend fetch error on the BB api stops happening. 
I am doing this for myself to learn, not to profit. 

When I see again other people similar to me, having the idea to move on and make the Phoenix rise again: I feel good in that this software is not really abandoned. It can grow and fulfill it's role, all with the help of volunteers. 

Changing a name is a technicality. Adding value to the world with the short time you are given in your life is priceless. Irregardless of getting 'credit' for something, it is more about your own internal reward, in the end.

I know this may sound crazy, but I have the love for you. Thank you for coming back and giving us some kind of acknowledgement that people were not unheard in some way. And thank you for a giving a s*** about BoxBilling, too! I can tell that you do, or you would not have taken it on here.

With that, I apologize if I came across as aggressive or insulting in any comments here. That is not my intention. I hope you understand I do care and that was the only reason I bothered to make a github account to comment here.

So now I would like to ask you to help make value for the world in a way that will enable you to reach your v5, as well. Because I understand it is hard to focus development where you want when you have to pay the bills. 

As you acknowledged this has already crippled the project's ability to gain traction. And, if this really is a step-child for you/your team, then this could be leveraged in to a win-win.

Let me explain, if I may. But right now, I thank you for all your time you have already given me here.

Continuing on, I know that your level of experience in the existing project would be invaluable to the CB fork. And BB would not have to end, either. But, by partnering with CB, you would have direct access and assistance in developing. You can already get work CB does back upstream to BB if you desire it. You get a free dev team for a new version out of this, either way. 

But if you were willing to help, then we could build a much more cohesive and productive environment, built on the work of the community that is already going to work on it anyway. 

The only question is, would you be willing? To bring your support and advice to CB would bring value to your time. You could help people who care and want success for you and your project, too. I don't think anyone at CB wants to "steal" your work. Only to help the project fulfill it's destiny and reach the level of greatness that it deserves.

And I honor you, that someone would fork your work. I hope if i can ever manage to get code on here that someone might want to fork it, too. And I hope I would want to support them and bring value to their life, too. 

So, again, I apologize. I am a little tearful, and fearful, that the possibility of someone with so much experience in the nuts and bolts of BB will never want to help CB because of stuff said out of frustration in this issue page.
I implore you to consider. 

Sincerely,
Malcolm R.

**Comment by gOOvER** [comment]
@namenodeis How many you get paid for this? Or is this from TuxMay an other account. I know he have more then one ;) Sorry, but i can'Ät believe your words, becasue teh BB Team only Talk and do nothing. I waste Money with this Team and never get any answer.

The Fork is the best Way to see, what happend, when others than the BB Tam working on it ;)

**Comment by TuxMay** [comment]
Hello Malcolm, I will continue to support BoxBilling, yet I will not support CircleBilling as CB as you are calling it is a completely separate development & is not apart of BoxBilling.

**Comment by namenodeis** [comment]
Alright then, @TuxMay, fair enough. Thank you for taking the time to read and reply. Best wishes to you and the BB team!
