### ISSUE TITLE
Not able to pass step 2 ... 

### ISSUE THREAD

**Issue by coolternet** [boxbilling/boxbilling#520]
no error message and no notification. simply stuck at Step 2

**Comment by psycholyzern** [comment]
Boxbilling is dead, find another alternatives.

**Comment by TuxMay** [comment]
Sorry, I didn't get the notification about this.

What PHP version are you using? Unfortunately, BoxBilling does not support PHP 7.x as if yet due to PHP functions that were deprecated with PHP 7.0 and above.

Please switch your PHP version to v5.6.x and try again, note that all required/recommended PHP extensions should also be active on the domain you are using.

**Comment by Eiskaltereistee** [comment]
Hi,

if you're looking for a working PHP7.2 version of boxbilling, you can follow us here: https://github.com/CircleBilling/CircleBilling

Otherwise, we recommend to use BoxBilling. To fix your problem, you should give us some more information about your problem.

- Please enable the debug mode in your bb-config.php
- Please check your apache (/var/log/apache2/error_log) or nginx error log (/var/log/nginx/error_log
- Check your bb-logs folder too: src/bb-data/log/php_error.log
- Also you should share your PHP and MySql Version.

Thank you and have a nice day!

**Comment by abhishekcsharp** [comment]
> no error message and no notification. simply stuck at Step 2

Selecting php 5.6 in cpanel with "my sql"  selected solved the issue for me
