### ISSUE TITLE
MYSQL 5.7 - 5.6 PROBLEM

### ISSUE THREAD

**Issue by djmarcoleiva** [boxbilling/boxbilling#529]
i'm experimenting this error on the new installations of cpanel 

An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'mediaweb_boxb124.stm.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") in "mod_index_dashboard.phtml" at line 29.

**Comment by TuxMay** [comment]
We are aware of this issue, it is caused by the way MySQL is set up, majority of hosting providers keep the default setup from installation.

It is caused by MySQL having a "ONLY_FULL_GROUP_BY" policy.
You can find this page helpful to disable it: https://stackoverflow.com/questions/23921117/disable-only-full-group-by
