### ISSUE TITLE
PHP 7 is supported, isn't it?

### ISSUE THREAD

**Issue by yagizhan49** [boxbilling/boxbilling#555]
I tried setting up BoxBilling 4.20 in my workplace.

But I've some some differences between the installer and the README.md in the master branch.

In the installer, I've been told that I'm using PHP 7.x and it was supported by the script, but in README.md, it states out that PHP 7 is not supported.

I think you might want to update the README.md file.

**Comment by g4m3r0** [comment]
I think it's not stated because it's no fully tested with newer PHP versions.

I tested the "recent" bb version and it seems like it works with PHP 7.0 & 7.1 but not with 7.2 & 7.3.
But I haven't checked every function or page.

**Comment by ms217** [comment]
mcrypt was removed from PHP 7.2 and onwards because libmcrypt is not actively developed anymore.
However, it's still possible to compile mcrypt support for PHP 7.2 and newer if one needs to.

Just grab the sources from https://pecl.php.net/package/mcrypt for that.

Either way, it's probably still better to ditch the code that relies on mcrypt since it is just a matter of time until the PECL package becomes also unmaintained.
