### ISSUE TITLE
PHP fatal error installing ==> "bb-vendor/autoload.php"? ==> HTTP ERROR 500

### ISSUE THREAD

**Issue by Nerque** [boxbilling/boxbilling#577]
Where are the folder bb-vendor and the autoload.php?

`[22-Feb-2020 13:02:17 UTC] PHP Fatal error:  require(): Failed opening required 'xxxx/xxxx/bb-vendor/autoload.php' (include_path='xxx/xxx/bb-library:.:/opt/plesk/php/5.6/share/pear') in xxx/xxx/install/index.php on line 47`

**Comment by g4m3r0** [comment]
Seems like the path in indicated incorrectly.
Try to add your full path to _/install/index.php on line 47_

**Comment by Nerque** [comment]
Okay, I could change it, but change it to what? The bb-vendor folder doesn't exist. Neither does the autoload.php.

**Comment by g4m3r0** [comment]
Do you want to build bb or just run it on a webserver?
If you just want to run in on a webserver only upload the content of the source folder.

**Comment by Nerque** [comment]
I uploaded the content to a web server, and this is what happens.
I copied the contents of the src folder to the root of the site. Is this correct?
I've done this because the link of the download page in boxbilling page, doesn't work (You don't have permission to access /bb-themes/bb2015/assets/ on this server.)
For this reason I thought that downloading from Github was the solution but... if the steps are to copy the content of the src folder to its destination... it doesn't work.

**Comment by g4m3r0** [comment]
Ops, I haven't seen that the new release (4.21) does not include any package.
You can install them by using [composer](https://getcomposer.org) update or download the once I attached.
They are freshly updated, but please note some packages are (very) out of date because they either were replaced or abandoned.

But I hope that the BB community will be active again soon and update everything :).
[bb-vendor.zip](https://github.com/boxbilling/boxbilling/files/4257004/bb-vendor.zip)
