### ISSUE TITLE
boxbilling.com error

### ISSUE THREAD

**Issue by wildfirebill** [boxbilling/boxbilling#600]
BoxBilling

PDOException was thrown when trying to read the session data: SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT command denied to user 'b099bd000cf904'@'ec2-3-84-211-129.compute-1.amazonaws.com' for table 'session'

Look for detailed error explanation

your site is throwing this error I was looking at purchasing a license

**Comment by timothygwebb** [comment]
Whoever owns the computer instance ec2-3-84-211-129.compute-1.amazonaws.com
needs to look at the database instance and the table sessions to verify
write access or that the table exists and is not damaged. I know how to do
this but I am not the owner of
http://ec2-3-84-211-129.compute-1.amazonaws.com/ and I do not have access.

**Comment by S4-Hosting** [comment]
Great that the site isn't throwing this error anymore, but it would be really good if the broken download button could be fixed, either to download directly (preferably a new release with PHP 7.2 support) or to direct to this github repo so that people know to download from here. 

Also the installation instructions on the site do not work as they are.

**Comment by rndevuk** [comment]
Can this now be closed?

**Comment by S4-Hosting** [comment]
Yes, this should be closed, the site is working. The download link isn't, but that's covered in another issue.

**Comment by timothygwebb** [comment]
> Yes, this should be closed, the site is working. The download link isn't, but that's covered in issue #613
