### ISSUE TITLE
License is not valid

### ISSUE THREAD

**Issue by toumi-mohamed** [boxbilling/boxbilling#608]
after Installing on my VPS I can't log in I get error License is not valid
I was using the free license

**Comment by OnlyHardOfficial** [comment]
You can baypass the lincense method

**Comment by weblle** [comment]
> You can baypass the lincense method

how does one do that? the license is valid but it isn't validating while logging in

**Comment by rndevuk** [comment]
@fordnox

**Comment by OnlyHardOfficial** [comment]
@rndevuk  @weblle @fordnox  ...
Well this is a a common litle bug you can make that already exists when the fordnox was no longer in the project.. anyway .. soo... search on google

**Comment by rndevuk** [comment]
@OnlyHardOfficial I know how to bypass it, But its not my job to pass that information on. this needs to be dealt with by @fordnox.
Personally I think the license system should be pulled out of the source, But that's not my call to make.

Either way we need a decision from @fordnox as to whether we should remove the licence system or he needs to fix it on his servers.

@fordnox this needs your input as a matter of priority :)

**Comment by timothygwebb** [comment]
@fordnox @OnlyHardOfficial @rndevuk  @weblle  @toumi-mohamed the error given occurs to me as well and what it means is that the registered account username and password is not being validated. I reset my password and the issue disappeared. The licensing is not the real issue and yes of course any real developer such as my self can decipher and reengineer the system but a code of ethics should be applied here and common sense. The licensing mechanism is put in place for the enabling of certain features after being paid for. If you remove the licensing feature you will remove the ability for profitable ownership. Just my little piece of mind. This issue is also related to admin is not logged in. I only get the error when I forget my password or don't put in the correct authentication credentials. Let me know your thoughts everyone.

**Comment by fordnox** [comment]
> @OnlyHardOfficial I know how to bypass it, But its not my job to pass that information on. this needs to be dealt with by @fordnox.
> Personally I think the license system should be pulled out of the source, But that's not my call to make.
> 
> Either way we need a decision from @fordnox as to whether we should remove the licence system or he needs to fix it on his servers.
> 
> @fordnox this needs your input as a matter of priority :)

This decision is not straight forward and I will not go down into my personal details here, but a short comment:

**This project has a chance of better future only if license check is removed. So my decision is to remove license check.**

**Comment by timothygwebb** [comment]
Good decision. Those of us who have an active paid license how is that
going to be dealt with?

**Comment by rndevuk** [comment]
@fordnox I'll get this done soon... il start by pushing a pr to disable the license system first.. and then il work on a pr to remove all the licence components.

@timothygwebb I would assume active licenses would seize to exist beyond that point..

What I would suggest though is that we make a page on the new website where @fordnox & all other contributors are listed and enable @fordnox & all other contributors to list their prefered paypal/patreon accounts along side info showing what their contribution to the source/docs is.

This way the community can donate to whom ever this feel deserves it.

I also think we should setup a bug/feature bounty system so that people can pay to have community developers fix issues and create features within the project thats important to them.... sort of a way to fast track things and encourage development.
I think there are a few systems that offer this functionality already...

**Comment by rndevuk** [comment]
https://www.bountysource.com is one site that could be used for source bountying

**Comment by timothygwebb** [comment]
Ryan,

This is a great idea. I am already an approved sponsor.
Your GitHub Sponsors profile is live at
https://github.com/sponsors/timothygwebb

**Comment by S4-Hosting** [comment]
> What I would suggest though is that we make a page on the new website where @fordnox & all other contributors are listed and enable @fordnox & all other contributors to list their prefered paypal/patreon accounts along side info showing what their contribution to the source/docs is.

Sounds like a reasonable idea, I think that before anyone worries about any of that though, the real matter of urgency is to change that existing website into a simple page linking to the Github repo to download latest release and removing all mention of the license. All of the time that there is mention of a license on that site it's confusing and puts people off. 

> I also think we should setup a bug/feature bounty system so that people can pay to have community developers fix issues and create features within the project thats important to them.... sort of a way to fast track things and encourage development.

Great idea, does anyone have any experience using any of these bounty systems?

**Comment by fordnox** [comment]
This got so wrong so quickly...

Guys, lets fix the project first, if you want money, you are in the wrong place.

**Comment by rndevuk** [comment]
Nobody said they wanted money.. I personally dont need it. 
But... as this is a community project now, you might find more people are happier to contribute their time to work on the project if their is a way for them to potentially get something out of it.

In community projects bugs/features often dont get fixed unless they affect the person thats willing to fix them... the bounty idea is designed to avoid this and is a common system used in alot of opensource projects.

**Comment by timothygwebb** [comment]
Ryan,

Said it like a pro. This project personally effects my company so I am
highly involved in this project. If it were not for that my only other
motivation would be to enhance my ability to develop using php and learn
more about the many things that can be done regarding continuous
integration and deployment. Once we get all the bugs fixed that is going to
be my next project. Getting this on go and deployed automatically on heroku.
