### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by CrIKxSLCD** [boxbilling/boxbilling#612]
Hello,

When I install boxbilling and get to step 3, it tells me to wait for the database except nothing happens. even after the database has been installed.

How to do ? I have no error logs

![37713ad74fca7fa664c85552d7ca9619](https://user-images.githubusercontent.com/31045399/90342083-a1aab900-e005-11ea-9149-04ed213347eb.png)

**Comment by CrIKxSLCD** [comment]
![3571629f053807571b9b93b74022150a](https://user-images.githubusercontent.com/31045399/90429482-1b09e080-e0c6-11ea-8077-03accb3d1c95.png)

**Comment by samapraku** [comment]
Since it is a 500 (Internal Server Error), the issue could be related to .htaccess file configurations if you are using apache.

You can start with your .htaccess file.

**Comment by rndevuk** [comment]
Hi @CrIKxSLCD Did you manage to solve this issue?

**Comment by timothygwebb** [comment]
@CrIKxSLCD You are using a content manager such as word press and you have a blocking extension causing the post method to fail on the install. I would remove the .htaccess file first and see if your problem disappears. Aside from that comment I am closing this issue due to the website mentioned in the issue account at hosting provider has been suspended. http://momonheberg.tk/cgi-sys/suspendedpage.cgi
