### ISSUE TITLE
Can't delete invoices from the admin area

### ISSUE THREAD

**Issue by tobias992** [boxbilling/boxbilling#808]
- sometimes i cant delete invoices -> ERROR "invoice was not found"

**Comment by notbasetwo** [comment]
I can't re-create this bug in my own environment. Is there anything remarkable about the invoices that you are having errors with @tobias992?

**Comment by BenNottelling** [comment]
I would be willing to bet that this was caused by that old issue which resulted in invoices being duplicated in the interface. (and then trying to delete one of the duplicated items)
We've fixed that issue now, and this ticket is almost a year old so I am going to close it.

But, if someone can reproduce it I would be happy to open a new one or re-open this
