### ISSUE TITLE
500 Error while accessing admin panel and login

### ISSUE THREAD

**Issue by ZetCreate** [boxbilling/boxbilling#851]
Hello! I'm Andrew Marevic and I have a problem which is just ERR 500. Main page is working fine. But when trying to use login or admin it's typing Error 500. Thanks for listening!

**Comment by bosdaring** [comment]
change 'sef_urls' => false, on bb-config.php, see [nginx.conf](https://github.com/boxbilling/boxbilling/blob/master/data/nginx.conf) if you are using nginx.

**Comment by kasperireland** [comment]
is boxbilling still safe to use?

**Comment by evrifaessa** [comment]
There are no _known_ problems with security. However, BoxBilling is not ready to be used on PHP 8 for now. The team is not active, and we need more contributors. I'm dealing with schoolwork rn. However, I'd still love to work on BB if I can find some active contributors to work with. If you want to work on known issues, head to the "issues" tab. @kasperireland, assuming you already know how, but for those who don't, I rewrote the README, you can find instructions on how to install BB on your development infrastructure.

**Comment by BenNottelling** [comment]
@kasperireland and @systemfreaks BoxBilling does have a few known vulnerabilities (but no known exploits) in it's current release, but we are working on a new release in about a week. 
I make no promise in terms of it being bug-free, but this release will include some security fixes.

Either way, I am closing this issue @ZetCreate as it seems that your problem was identified and resolved. If you have problems please either update this ticket or create a new one
