### ISSUE TITLE
Jump to cPanel button doesnt work!

### ISSUE THREAD

**Issue by comfyyy** [boxbilling/boxbilling#888]
Jump to cPanel button doesnt work! When clicked on that button it redirects to google.. Do note that it also happened to the login to WHM button. Is there anything I can do to fix this?

**Comment by BenNottelling** [comment]
What server manager?

**Comment by timothygwebb** [comment]
@BenNottelling @comfyyy Server Manager is a file that is used during the domain name registration process. It is what is used when talking with your API to do your registration tasks. The most likely cause for the google is because of the following. https://gist.github.com/boxbilling/1801871/revisions. The link preferencing's  of this statement was the original CustomManager example to be used when building different connections to different registrars such as internet.bs or WHM. Let me know if this makes since or if you need further clarification.

**Comment by BenNottelling** [comment]
> @BenNottelling @comfyyy Server Manager is a file that is used during the domain name registration process. It is what is used when talking with your API to do your registration tasks. The most likely cause for the google is because of the following. https://gist.github.com/boxbilling/1801871/revisions. The link preferencing's of this statement was the original CustomManager example to be used when building different connections to different registrars such as internet.bs or WHM. Let me know if this makes since or if you need further clarification.

I know what the server manager is. I was asking which one he's using since as far as I know the only one that has google is the "custom" one

**Comment by timothygwebb** [comment]
@BenNottelling @comfyyy I have fixed this at one time in a prior commit if you are using this in relation to the Plesk jump to cPanel function. Plesk has modified their software and this feature will need to be reviewed by a Plesk user besides myself because I have closed my company and I am now a full time contractor. You are correct most likely using the Custom.

**Comment by comfyyy** [comment]
I was using cPanel, but dont worry, I have moved to Blesta

**Comment by BenNottelling** [comment]
> I was using cPanel, but dont worry, I have moved to Blesta

The cPanel manager should have opened the correct URL. You either accidentally selected "custom" in the server type, or there is an actual bug inside BoxBilling that causes it to use the wrong manager when it calls that function. I'm assuming it was configured incorrectly.

**Comment by BenNottelling** [comment]
I'm going to close this as I believe it was due to user error, but if that ends up not being the case anyone is welcome to leave a comment and I'll re-open, or they can create a new issue. 
Regardless, the Cpanel server manager should probably be rewritten
